In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline

In [2]:
marks=pd.read_csv(r'C:\Users\ELCOT\Documents\Machine learning\Classification\Marks.csv')

In [3]:
marks.head()

e1_score   e2_score  result
0  34.623660  78.024693       0
1  30.286711  43.894998       0
2  35.847409  72.902198       0
3  60.182599  86.308552       1
4  79.032736  75.344376       1

In [4]:
marks.isnull().sum()

e1_score    0
e2_score    0
result      0
dtype: int64

In [5]:
marks.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 141 entries, 0 to 140
Data columns (total 3 columns):
e1_score    141 non-null float64
e2_score    141 non-null float64
result      141 non-null int64
dtypes: float64(2), int64(1)
memory usage: 3.4 KB


In [6]:
X=marks.iloc[:,:2].values

In [7]:
y=marks.iloc[:,2].values

In [8]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.25,random_state=42)

In [9]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(105, 2)
(36, 2)
(105,)
(36,)


In [10]:
from sklearn.linear_model import LogisticRegression
logr=LogisticRegression()
logr.fit(X_train,y_train)
y_pred=logr.predict(X_test)


C:\Users\ELCOT\Documents\New folder\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


In [11]:
parameters=logr.coef_
print(parameters)

[[0.04150805 0.03601657]]


In [12]:
from sklearn.metrics import accuracy_score
print('Accuracy:',accuracy_score(y_pred,y_test))


Accuracy: 0.8888888888888888


In [13]:
logr.intercept_

array([-4.36288502])

In [14]:
logr.coef_

array([[0.04150805, 0.03601657]])

In [15]:
logr.predict(X_test)

array([1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0], dtype=int64)